development:
  bucket: 'static.eightpm.tv'
  access_key_id: AKIAJXZ66TNJSUDJPNHQ
  secret_access_key: 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
  backup: 'backups.eightpm.tv'
    
production:
  bucket: 'static.eightpm.tv'
  access_key_id: AKIAJXZ66TNJSUDJPNHQ
  secret_access_key: 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
  backup: 'backups.eightpm.tv'

staging:
  bucket: 'static.eightpm.tv'
  access_key_id: AKIAJXZ66TNJSUDJPNHQ
  secret_access_key: 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
  backup: 'backups.eightpm.tv'
  