development:
  bucket: 'rmgalite-tvshows'
  access_key_id: AKIAJXZ66TNJSUDJPNHQ
  secret_access_key: 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

production:
  bucket: 'rmgalite-tvshows'
  access_key_id: AKIAJXZ66TNJSUDJPNHQ
  secret_access_key: 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

