development:
  bucket: 'static.eightpm.tv'
  access_key_id: AKIAJXZ66TNJSUDJPNHQ
  secret_access_key: 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

production:
  bucket: 'static.eightpm.tv'
  access_key_id: AKIAJXZ66TNJSUDJPNHQ
  secret_access_key: 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

staging:
  bucket: 'static.eightpm.tv'
  access_key_id: AKIAJXZ66TNJSUDJPNHQ
  secret_access_key: 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
  